#!/bin/sh

set -e

accounts=(
	personal
	upmail
)

tag_folder() {
	local folder="$1"
	shift

	notmuch tag "$@" -- folder:\""/$account/$folder/"\"
}

for account in "${accounts[@]}"; do
	tag_folder "Archive" -trash -spam +"$account"
	tag_folder "Inbox" +inbox -trash -spam +"$account"
	tag_folder "Sent" +sent -trash -spam +"$account"
	tag_folder "Drafts" -trash -spam +drafts +"$account"
	tag_folder "Spam" +spam -trash +"$account"
	tag_folder "Trash" +trash +"$account"
done

notmuch tag -new -- tag:new
