#!/bin/sh

set -e

accounts=(
	personal
	upmail
)

folder_tags=(
	reference
	inbox
	spam
	trash
	draft
	sent
)

emit_folder_rule() {
	local folder="/$account\/$2/"
	printf '+%s +%s -- (tag:renew or tag:new) and folder:"%s"\n' "$1" "$account" "$folder"
}

emit_account_rules() {
	local account=$1

	emit_folder_rule "draft" "Drafts"
	emit_folder_rule "inbox" "Inbox"
	emit_folder_rule "reference" "Reference"
	emit_folder_rule "sent" "Sent"
	emit_folder_rule "spam" "Spam"
	emit_folder_rule "trash" "Trash"
}

generate_batch_tag() {
	printf '%s\n' \
		"+renew -- lastmod:-1.." \
		'-trash -spam -inbox -draft -sent -reference -- tag:renew'

	for account in "${accounts[@]}"; do
		emit_account_rules "$account"
	done

	printf '%s\n' \
		'-renew -- tag:renew' \
		'-new -- tag:new'
}

generate_batch_tag | notmuch tag --batch

#notmuch tag -new -- tag:new
