#!/bin/sh

alias nmsearch="$(command -v notmuch) search --exclude=false --output=files --"
maildir=$(notmuch config get database.path)

move_tagged() {

	local IFS=$'\n'
	local tag="$1"
	local folder=$(printf '%q' "$2" | sed 's/\//\\\//g')

	for f in $(nmsearch tag:"$tag" and not folder:"\"/$folder/\""); do
		new=$(echo "$f" | sed "s;$maildir/\([^/]*\)/.*/cur/;$maildir/\1/$folder/cur/;" | sed 's/,U=[0-9]*:/:/')

		[ -f "$f" ] && mv -v "$f" "$new"
		#echo "rename: $f -> $new"
	done
}

move_tagged inbox "INBOX"
