maildir: ~/.mail
rename: true
rule_match_mode: first
rules:
  - folder: "personal/[Gmail]/Trash"
    query: tag:personal and tag:trash
    prefix: personal

  - folder: "personal/[Gmail]/Spam"
    query: tag:personal and tag:spam
    prefix: personal

  - folder: "personal/INBOX"
    query: tag:personal and tag:inbox
    prefix: personal

  - folder: "personal/[Gmail]/All Mail"
    query: tag:personal
    prefix: personal

  - folder: "upmail/[Gmail]/Trash"
    query: tag:upmail and tag:trash
    prefix: upmail

  - folder: "upmail/[Gmail]/Spam"
    query: tag:upmail and tag:spam
    prefix: upmail

  - folder: "upmail/INBOX"
    query: tag:upmail and tag:inbox
    prefix: upmail

  - folder: "upmail/[Gmail]/All Mail"
    query: tag:upmail
    prefix: upmail

