maildir: ~/.mail
rename: true
rule_match_mode: unique
rules:
  - folder: "personal/Trash"
    query: tag:personal and tag:trash
    prefix: personal

  - folder: "personal/Spam"
    query: tag:personal and tag:spam
    prefix: personal

  - folder: "personal/Inbox"
    query: tag:personal and tag:inbox
    prefix: personal

  - folder: "personal/Drafts"
    query: tag:personal and tag:draft
    prefix: personal

  - folder: "personal/Sent"
    query: tag:personal and tag:sent
    prefix: personal

  - folder: "personal/Reference"
    query: tag:personal and tag:reference
    prefix: personal

  - folder: "upmail/Trash"
    query: tag:upmail and tag:trash
    prefix: upmail

  - folder: "upmail/Spam"
    query: tag:upmail and tag:spam
    prefix: upmail

  - folder: "upmail/Inbox"
    query: tag:upmail and tag:inbox
    prefix: upmail

  - folder: "upmail/Drafts"
    query: tag:upmail and tag:draft
    prefix: upmail

  - folder: "upmail/Sent"
    query: tag:upmail and tag:sent
    prefix: upmail

  - folder: "upmail/Reference"
    query: tag:upmail and tag:reference
    prefix: upmail

