typeset -U path
path=(~/.texlive/2023/bin/x86_64-linux $path)
# rubygem bins
export GEM_HOME="$(gem env user_gemhome)"
path=($GEM_HOME/bin $path)

typeset -U manpath
manpath=(~/.texlive/2023/texmf-dist/doc/man $manpath)

export -TU INFOPATH infopath
infopath=(~/.texlive/2023/texmf-dist/doc/info $infopath)

export WLR_RENDERER=vulkan
export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1

export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock

export XDG_CURRENT_DESKTOP=sway

export QT_QPA_PLATFORMTHEME=qt5ct

export QT_QPA_PLATFORM=xcb

# text input envs
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

export EDITOR=nvim
