typeset -U path
path=(
		~/.local/texlive/2026/bin/x86_64-linux
		~/.local/bin
		$path
)

# rubygem bins
export GEM_HOME="$(gem env user_gemhome)"
path=($GEM_HOME/bin $path)

export -TU INFOPATH infopath
infopath=(~/.local/texlive/2026/texmf-dist/doc/info $infopath)

export WLR_RENDERER=vulkan
export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1

export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock

export QT_QPA_PLATFORMTHEME=qt5ct

export QT_QPA_PLATFORM=xcb

# text input envs
export XMODIFIERS=@im=fcitx

export EDITOR=nvim

export BROWSER=mozilla

export NOTMUCH_CONFIG=~/.config/notmuch/config

export LESS=-Ri

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
